### PR TITLE
(API/SERV)🚚 Moving report generation from service layer

### PR DESCRIPTION
**Pull request by malcolmdzimati**

### CODE REVIEW

**Comment by Ivy-leet** [comment]
The move will make add custom tweets not work @malcolmdzimati

**Comment by malcolmdzimati** [comment]
> The move will make add custom tweets not work @malcolmdzimati

how so?

**Comment by Ivy-leet** [comment]
Custom tweets relies on the get report service layer to return the number of blocks in the report.

**Comment by malcolmdzimati** [comment]
> Custom tweets relies on the get report service layer to return the number of blocks in the report.

I am thinking of changing that logic, I will get all the blocks of a report get the highest position and place the tweet at the next positive interger

**Review by Ivy-leet — DISMISSED** [review]

**Review by Ivy-leet — APPROVED** [review]

**Review by Zenthon — APPROVED** [review]

**Pull request merged**
