### PR TITLE
🐛 ⚡ Added null values

### PR DESCRIPTION
**Pull request by malcolmdzimati**

### CODE REVIEW

**Comment by Zenthon** [comment]
Please fix the failing test

**Comment by Ivy-leet** [comment]
Will change test due to change in report object structure

**Comment by Zenthon** [comment]
So we must merge with the failing test?

**Comment by Zenthon** [comment]
If we do, every PR that comes after is guaranteed to fail

**Comment by Ivy-leet** [comment]
AM fixing it. This PR shouldn't be merged if tests fail

**Comment by Ivy-leet** [comment]
@Zenthon Next time when tests are failing in the service folder please @ me and I'll try to fix it as soon as I can, and the pr must not be merged in. This can be caused by the change of structure of what is being returned by the functions in the service folder

**Comment by Zenthon** [comment]
Noted.

**Comment by Zenthon** [comment]
I'll merge it in

**Review by Zenthon — APPROVED** [review]

**Pull request merged**
