### PR TITLE
🎨 ✨ Added clone report endpoint as well as restructured backend/API to be object oriented, as well as changed certain endpoints.

### PR DESCRIPTION
**Pull request by malcolmdzimati**
Restructuring back-end: Back end has been restructured(in a similar manner to the service layer) such that each folder represents a certain object/entity within the system and all of the functions that are directly based on that entity are stored within that entity folder and handler. E.g report: the report handler and folder will contain all functions that have to do with reports: report creation, report management and report sharing etc etc.

Change of Endpoints: Some endpoints and functions name have been changed to be less ambiguous, namely search, getAllMyReports and getAllReports, these have been changed to searchTweets, getAllMyDraftReports and getAllPublishedReports respectively.

### CODE REVIEW

**Comment by Ivy-leet** [comment]
@GO-Shoderu @jonahgasura the endpoints are going to change due to this pr. @Zenthon will the stack have to be rebuilt?

**Comment by malcolmdzimati** [comment]
I doubt the stack will need to be reformed but let's see what JJ says.

**Comment by Zenthon** [comment]
The endpoints will change

**Comment by Zenthon** [comment]
@malcolmdzimati You'll need to test with frontend that all the changed endpoints still work on their side

**Review by Zenthon — APPROVED** [review]
All looks good. Good to merge

**Comment by GO-Shoderu** [comment]
I will check all the endpoints by Sunday ... My internet has been cut off because of technical issues with Telkom ....

**Pull request merged**
