### PR TITLE
🐛 🧪 Fixing failing tests

### PR DESCRIPTION
**Pull request by malcolmdzimati**

### CODE REVIEW

**Comment by Zenthon** [comment]
2 tests failed

**Comment by Zenthon** [comment]
After writing/ making changes to the tests, run: yarn test

**Comment by Zenthon** [comment]
Internal Server Error
      at Request.Object.<anonymous>.Request.callback (node_modules/superagent/src/node/index.js:900:17)
      at callback (node_modules/superagent/src/node/index.js:1[15](https://github.com/COS301-SE-2022/Twitter-Summariser/runs/7147441517?check_suite_focus=true#step:5:16)3:[18](https://github.com/COS301-SE-2022/Twitter-Summariser/runs/7147441517?check_suite_focus=true#step:5:19))
      at IncomingMessage.fn (node_modules/superagent/src/node/parsers/json.js:[19](https://github.com/COS301-SE-2022/Twitter-Summariser/runs/7147441517?check_suite_focus=true#step:5:20):7)
  ● Given an authorised request WHEN the post generateReport endpoint is called › THEN it should respond with a healthy body

**Comment by malcolmdzimati** [comment]
I am thinking of removing the tests, cause I don't know why the are not working

**Comment by malcolmdzimati** [comment]
If they fail now, I will comment them out and try figure out whats wrong with them

**Comment by Zenthon** [comment]
Ok. no stress

**Comment by malcolmdzimati** [comment]
I think it might be a limit on the number of requests being made per second, but either way I will fix it later

**Review by Zenthon — APPROVED** [review]

**Pull request merged**
