### PR TITLE
💄 ✨ ⚡️ 🎨 (UI): Added new component called text

### PR DESCRIPTION
**Pull request by GO-Shoderu**
Added new component called text and also created the text editor

### CODE REVIEW

**Review by Zenthon — DISMISSED** [review]

**Comment by Zenthon** [comment]
@GO-Shoderu Module not found: Error: Can't resolve 'axios' in '/home/runner/work/Twitter-Summariser/Twitter-Summariser/client/src/components/Home'


Please fix this

**Comment by GO-Shoderu** [comment]
I can't I've tried looking for why that error exist but I don't know why ... 
can we have a quick discord session?

**Comment by Zenthon** [comment]
Awe. Im going there now

**Review by Zenthon — APPROVED** [review]
All tests passed. All looks good

**Pull request merged**
