### PR TITLE
🔥🚚 🚀 (CICD): Renamed IDs for hosting + Stopped Model from being deployed

### PR DESCRIPTION
**Pull request by Zenthon**

### CODE REVIEW

**Comment by Ivy-leet** [comment]
Was is the model not being deployed?

**Comment by Zenthon** [comment]
Im busy working on it

**Review by Ivy-leet — APPROVED** [review]
Please state the issues encountered with the text summarization model for you to decide not to deploy it by replying to this.

**Comment by Zenthon** [comment]
There aren't any issues. I need to redownload the config files (which are very large) and upload them to aws. I'll do it tomorrow

**Pull request merged**
